import type { VercelRequest, VercelResponse } from '@vercel/node';

export interface BlogPostItem {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  author: string;
  date: string;
  readTime: string;
  imageUrl: string;
  sourceUrl?: string;
  autoGenerated?: boolean;
}

let CENTRAL_BLOG_POSTS: BlogPostItem[] = [
  {
    id: 'regras-da-ans-para-portabilidade-de-carencias-sem-cumprimento-de-novos-prazos',
    slug: 'regras-da-ans-para-portabilidade-de-carencias-sem-cumprimento-de-novos-prazos',
    title: 'Regras da ANS para portabilidade de carências sem cumprimento de novos prazos',
    excerpt: 'Confira os principais detalhes sobre as novas diretrizes da ANS para portabilidade de carências sem novos prazos e como orientar seus clientes.',
    content: `<p>A <strong>Agência Nacional de Saúde Suplementar (ANS)</strong> divulgou atualizações normativas sobre as regras de <strong>Portabilidade de Carências</strong> para beneficiários de planos de saúde em todo o país.</p><h2>O que muda para os Beneficiários</h2><p>As novas diretrizes simplificam a migração entre planos compatíveis de operadoras sem a necessidade de cumprir novos períodos de carência ou cobertura parcial temporária (CPT), desde que observados os requisitos de permanência mínima no plano de origem.</p><h2>Oportunidade para Corretores de Saúde</h2><p>Para os corretores, o entendimento claro das regras da ANS possibilita oferecer consultoria ágil aos clientes que buscam aprimorar sua cobertura ou reduzir custos. Utilize o <strong>Simulador On-Line</strong> para cotar opções compatíveis em tempo real!</p>`,
    category: 'Regulamentação',
    author: 'Redação Simulador On-Line',
    date: '25 de Agosto, 2026',
    readTime: '4 min de leitura',
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&q=80&w=1200',
    sourceUrl: 'https://www.gov.br/ans',
    autoGenerated: true
  },
  {
    id: 'hapvida-confirma-reajuste-cancelamento-947-mil-contratos',
    slug: 'hapvida-confirma-reajuste-cancelamento-947-mil-contratos',
    title: 'Hapvida confirma reajuste ou cancelamento de 947 mil contratos',
    excerpt: 'Companhia revisa portfólio corporativo e promove ajustes em quase um milhão de vidas sob acompanhamento da ANS.',
    content: `<p>A <strong>Hapvida NotreDame Intermédica</strong> confirmou recentemente passar por um processo de reestruturação que envolve a revisão contratual de aproximadamente <strong>947 mil vidas</strong> em sua carteira de planos coletivos corporativos e de adesão.</p><p>Segundo executivos da operadora, a medida visa restabelecer o equilíbrio físico-financeiro de contratos que apresentaram sinistralidade elevada acima dos padrões regulatórios fixados pela Agência Nacional de Saúde Suplementar (ANS).</p><h2>Principais Impactos para Corretores e Clientes</h2><p>As alterações envolvem a aplicação de reajustes alinhados aos custos médicos ou o encerramento amigável de contratos deficitários com o devido aviso prévio de 60 dias estabelecido pela RN 557 da ANS.</p><p>Para corretores de seguros, o movimento abre uma janela importante de oportunidade de migração de carteira e oferta de novas alternativas de planos de saúde PME e Adesão.</p>`,
    category: 'Mercado',
    author: 'Redação Simulador On-Line',
    date: '25 de Agosto, 2026',
    readTime: '4 min de leitura',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=1200',
    sourceUrl: 'https://www.metropoles.com/brasil/economia-br/hapvida-confirma-reajuste-ou-cancelamento-de-947-mil-contratos',
    autoGenerated: false
  }
];

export default function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // GET: Listar todos os posts do blog
  if (req.method === 'GET') {
    return res.status(200).json(CENTRAL_BLOG_POSTS);
  }

  // PUT: Editar um post existente
  if (req.method === 'PUT') {
    const { id, title, excerpt, content, category, imageUrl, sourceUrl, pin } = req.body || {};

    if (pin !== '2026' && pin !== 'simulador') {
      return res.status(401).json({ error: 'Senha de acesso incorreta' });
    }

    const postIndex = CENTRAL_BLOG_POSTS.findIndex(p => p.id === id || p.slug === id);
    if (postIndex === -1) {
      return res.status(404).json({ error: 'Artigo não encontrado para edição' });
    }

    CENTRAL_BLOG_POSTS[postIndex] = {
      ...CENTRAL_BLOG_POSTS[postIndex],
      title: title ? title.trim() : CENTRAL_BLOG_POSTS[postIndex].title,
      excerpt: excerpt ? excerpt.trim() : CENTRAL_BLOG_POSTS[postIndex].excerpt,
      content: content || CENTRAL_BLOG_POSTS[postIndex].content,
      category: category || CENTRAL_BLOG_POSTS[postIndex].category,
      imageUrl: imageUrl || CENTRAL_BLOG_POSTS[postIndex].imageUrl,
      sourceUrl: sourceUrl || CENTRAL_BLOG_POSTS[postIndex].sourceUrl
    };

    return res.status(200).json({
      success: true,
      post: CENTRAL_BLOG_POSTS[postIndex]
    });
  }

  // POST: Adicionar um novo post (Robô IA ou Manual)
  if (req.method === 'POST') {
    const { title, excerpt, content, category, imageUrl, sourceUrl } = req.body || {};

    if (!title || !content) {
      return res.status(400).json({ error: 'Título e conteúdo são obrigatórios' });
    }

    const slug = title
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');

    const newPost: BlogPostItem = {
      id: `${Date.now()}-${slug.substring(0, 30)}`,
      slug,
      title: title.trim(),
      excerpt: excerpt || title.substring(0, 150),
      content,
      category: category || 'Mercado',
      author: 'IA Simulador On-Line',
      date: new Date().toLocaleDateString('pt-BR', { day: '2-digit', month: 'long', year: 'numeric' }),
      readTime: '4 min de leitura',
      imageUrl: imageUrl || 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&q=80&w=1200',
      sourceUrl: sourceUrl || 'https://www.ans.gov.br',
      autoGenerated: true
    };

    CENTRAL_BLOG_POSTS.unshift(newPost);

    return res.status(201).json({
      success: true,
      post: newPost
    });
  }

  // DELETE: Apagar post pelo ID/slug (com autenticação por senha)
  if (req.method === 'DELETE') {
    const { id, pin } = req.body || req.query || {};

    if (pin !== '2026' && pin !== 'simulador') {
      return res.status(401).json({ error: 'Senha de acesso incorreta' });
    }

    if (!id) {
      return res.status(400).json({ error: 'ID do post é obrigatório' });
    }

    const initialCount = CENTRAL_BLOG_POSTS.length;
    CENTRAL_BLOG_POSTS = CENTRAL_BLOG_POSTS.filter(p => p.id !== id && p.slug !== id);

    if (CENTRAL_BLOG_POSTS.length === initialCount) {
      return res.status(404).json({ error: 'Artigo não encontrado no catálogo' });
    }

    return res.status(200).json({
      success: true,
      message: 'Artigo removido com sucesso do blog central'
    });
  }

  return res.status(405).json({ error: 'Método não permitido' });
}
